version: '3.9'

services:
  redis6371:
    image: redis:latest
    container_name: redis6371
    command: ["redis-server", "--requirepass", "key_admin", "--port", "6371"]
    ports:
      - "6371:6371"
    healthcheck:
      test: ["CMD", "redis-cli", "-h", "localhost", "-p", "6371", "-a", "key_admin", "ping"]
      interval: 30s
      timeout: 10s
      retries: 3

  typescriptsandboxservice:
    build:
      context: .
      target: development
    command: npm run service
    container_name: typescriptsandboxservice
    volumes:
      - .:/app
      - ./node_modules:/app/node_modules
    ports:
      - "3002:3002"
    environment:
      - NODE_ENV=development
    depends_on:
      redis6371:
        condition: service_healthy
    healthcheck:
      test: curl --fail http://localhost:3002 || exit 1
      interval: 5s
      timeout: 4s
      retries: 50
